### PR TITLE
Add health check to my apps

### PR DESCRIPTION
**Pull request by machristie**
This is a work-in-progress implementation of adding health check to the My Appliances page, as per issue #18 .

Remaining TODOs:
- [x] Add a modal popup when Delete is clicked when there are default credentials available for the cloud and ask the user if they also want to also delete the appliance
- [x] Add a launch history page
- [ ] attention is needed to change the name of My Appliances and the text to reflect these updates to the UI
- [x] getKP should just get the keypair from the `launchTask` instead of assuming it will be the latest_task

Those are the main remaining TODOs off the top of my head, but there are probably a few other UI tweaks we'll still want.

### CODE REVIEW

**Comment by afgane** [comment]
Did you end up switching to postgres locally to avoid Celery dying due to the locked sqlite?

**Comment by machristie** [comment]
@afgane No, I'm still using sqlite and just restart it every time it fails.

**Comment by machristie** [comment]
For some reason when I launched an Ubuntu instance the keyPair field in the launch task result had a null `material` value. So I wasn't able to successfully test displaying the keypair material.  I'm not sure if it is just the Ubuntu appliance or what.

**Comment by afgane** [comment]
@machristie If a key with the given name exists under the current account, the key will just be reused and hence no `material` will be available so that's the expected behavior.

**Comment by machristie** [comment]
@afgane ok, thanks. I guess I'm not sure how to test the retrieval of the material then. Would you be able to test it?

**Comment by nuwang** [comment]
@machristie This is looking great! Let's make it go live.

**Pull request merged**
